/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:1157d51a-b703-48cc-b269-280b37227cfd",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_PYHg1SbLY",
    "aws_user_pools_web_client_id": "74r70vaaiscpma78ol6u1ia688",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uk3wmwdijrh5hcpahkxvleeyla.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
